---
layout: post
title: Go 简明教程
date: 2022-04-30 05:30:00 +0800
categories: [Go]
tags: [Go]
---
go语句后面不用加分号

nil:一般认为err != nil时为失败。
## 条件判断
if ,for语句的条件没有圆括号,

go没有while

注：不能将左大括号放在下一行
```
 
for i := 0; i<10; i++{
     fmt.Println(i)
}
```
//精简的for语句

```
i := 1
for i<10 {
    fmt.Println(i)
    i++
}
```
//死循环，相当于for(;;)
```
 
i :=1
for {
    if i>10 {
        break
    }
    i++
}
```
## 变量
go是静态类型语言，值必须有类型

反过来声明变量类型

```
//声明初始化一个变量
var  x int = 100   //等价于 x := 100
//声明初始化多个变量
var i, j, k int = 1, 2, 3
```
只有在函数内部，可以用简洁的赋值写法:=
变量可以像import那样用区块一样声明，const，type 也是
```
var (
	ToBe   bool       = false
	MaxInt uint64     = 1<<64 - 1
	z      complex128 = cmplx.Sqrt(-5 + 12i)
)

const (
	Unknown = 0
	Female = 1
	Male = 2
)
```
变量的类型转换，需要明确指定，不能像c一样进行隐含转换。

## 常量
const s string = "hello world"
常量不能用:=语法

数组
``` 
var arr1 [5]int   //注意int紧挨着，没有空格
长度len(arr1)
b := [5]int{1, 2, 3, 4, 5}

b := a[2:4] // a[2] 和 a[3]
b = a[:4] // 从 a[0]到a[3]
b = a[2:] // 从 a[2]到a[4]
switch
没有break，可以使用逗号case多个值

 
switch i {
    case 1:
        fmt.Println("one")
    case 2:
        fmt.Println("two")
    case 3:
        fmt.Println("three")
    case 4,5,6:
        fmt.Println("four, five, six")
    default:
        fmt.Println("invalid value!")
}
```
## map
即哈希表或dict

```
func main(){
    m := make(map[string]int) //使用make创建一个空的map
 
    m["one"] = 1
    m["two"] = 2
    m["three"] = 3
    //长度len(m)为3   
 
    v := m["two"] //从map里取值，2
   
    delete(m, "two")  //删除了two  
 
    m1 := map[string]int{"one": 1, "two": 2, "three": 3}
    
    for key, val := range m1{
        fmt.Printf("%s => %d \n", key, val) // 如one => 1      
    }
}
```
## 指针
```
var i int= 1
var pInt *int= &i  //注意*号位置，*pInt=1

*pInt = 2  //i=2
i = 3  //*pInt=3


var p *[]int = new([]int)   // 分配内存，还没有初始化；*p == nil；一般很少使用
fmt.Println(p) //输出：&[]
 
*p = make([]int, 10, 10) //make([]int, 10, 100) //分配一个整型数组，长度为10，容量为100，并返回前10个数组的切片
fmt.Println(p) //输出：&[0 0 0 0 0 0 0 0 0 0]
fmt.Println( (*p)[2] ) //输出： 0
 
var v []int = make([]int, 10) // 已初始化了 ，或v := make([]int, 10)
fmt.Println(v) //输出：[0 0 0 0 0 0 0 0 0 0]
```
## 函数
反过来声明函数返回值
```
 
func max(a int, b int) int{  
    
}
返回多个值,如一个正常值，一个错误：

 
func multi_ret(key string) (int, bool){
    m := map[string]int{"one": 1, "two": 2, "three": 3}
 
    var err bool
    var val int
 
    val, err = m[key]
 
    return val, err
}

func main(){
    v, e := multi_ret("one")
    fmt.Println(v,e) //输出 1 true
 
    v, e = multi_ret("four")
    fmt.Println(v,e) //输出 0 false
 
    //一般这么用(注意分号后有e)
    if v, e = multi_ret("four"); e {
        // 正常
    }else{
        // 出错
    }
}
```
### 不定参数
```
func sum(nums ...int) {
    fmt.Print(nums, " ")  //输出如 [1, 2, 3] 之类的数组
    total := 0
    for _, num := range nums { 
        total += num
    }
    fmt.Println(total)
}
func main() {
    sum(1, 2)
    sum(1, 2, 3)

    nums := []int{1, 2, 3, 4}
    sum(nums...)//传数组
}
```
### 函数闭包
return返回的匿名函数记住了nextNum中i+j的值，并改变了i,j的值，于是形成了一个闭包的用法

```
func nextNum() func() int{// 可将 func() int 整体看成一个类型
    i,j := 1,1
    return func() int{
        var tmp = i+j
        i, j = j, tmp
        return tmp
    }
}
//main函数中是对nextNum的调用，主要是打出下一个斐波拉契数
func main(){
    nextNumFunc := nextNum()
    for i:=0; i<10; i++ {
        fmt.Println(nextNumFunc())
    }
}
```
### 接口和多态
```
//接口
type shape interface {
    area() float64 //计算面积
    perimeter() float64 //计算周长
}
 
//长方形
type rect struct{
    width, height float64
}
 
func (r *rect) area() float64 { //面积
    return r.width * r.height
}
 
func (r *rect) perimeter() float64 { //周长
    return 2*(r.width + r.height)
}
 
//圆形
type circle struct{
    radius float64
}
 
func (c *circle) area() float64 { //面积，同名方法
    return math.Pi * c.radius * c.radius
}
 
func (c *circle) perimeter() float64 { //周长
    return 2 * math.Pi * c.radius
}
 
//接口的使用
func interface_test() {
    r := rect {width:2.9, height:4.8}
    c := circle {radius:4.3}
 
    s := []shape{&r, &c} //通过指针实现
 
    for _, sh := range s {
        fmt.Println(sh)
        fmt.Println(sh.area())
        fmt.Println(sh.perimeter())
    }
}
```
## 结构体
c的
```
 
typedef struct SVCContext {
		int max_nal_size;	
} SVCContext;
go的

 
type Person struct{
    name string
    age  int
    email string
}
 
func main() {
    //初始化
    person := Person{"Tom", 30, "tom@gmail.com"}
    person = Person{name:"Tom", age: 30, email:"tom@gmail.com"}
 
    fmt.Println(person) //输出 {Tom 30 tom@gmail.com}
 
    pPerson := &person
 
    fmt.Println(pPerson) //输出 &{Tom 30 tom@gmail.com}
 
    pPerson.age = 40
    person.name = "Jerry"
    fmt.Println(person) //输出 {Jerry 40 tom@gmail.com}
}
```
### 结构体方法
Go没有public, protected, private关键字，如果想让一个方法可以被别的包访问，需要把这个方法的第一个字母大写。（小写的可以在整个包内被访问到）

```
type rect struct{
    width, height int
}
 
func (r *rect) area() int{ //求面积
    return r.width * r.height
}
 
func (r *rect) perimeter() int{ //求周长
    return 2*(r.width + r.height)
}
 
func main() {
    r := rect{width: 10, height: 15}
 
    fmt.Println("面积: ", r.area())
    fmt.Println("周长: ", r.perimeter())
 
    rp := &r
    fmt.Println("面积: ", rp.area())
    fmt.Println("周长: ", rp.perimeter())
}
```
## 错误处理
### Error接口
多值返回可以让我们更容易的返回错误，通常情况下，错误的类型是error，它是一个内建的接口类型。
```
 
type error interface {
    Error() string
}
示例：

 
package main

import "fmt"
import "errors"
 
//自定义
type myError struct {
    arg    int
    errMsg string
}
//重写实现Error接口
func (e *myError) Error() string {
    return fmt.Sprintf("%d - %s", e.arg, e.errMsg)
}
 
//两种出错
func error_test(arg int) (int, error) {
    if arg < 0  {
         return -1, errors.New("Bad Arguments - negtive!")
     }else if arg >256 {
        return -1, &myError{arg, "Bad Arguments - too large!"}
    }
    return arg*arg, nil
}
 
//测试
func main() {
    for _, i := range []int{-1, 4, 1000} {
        if r, e := error_test(i); e != nil {
            fmt.Println("failed:", e)
        } else{
            fmt.Println("success:", r)
        }
    }
}
```
输出
```
failed: Bad Arguments - negtive!
success: 16
failed: 1000 - Bad Arguments - too large!
```
### Defer

下面的代码有资源泄露的问题，C++使用RAII来解决这种问题

```
func CopyFile(dstName, srcName string) (written int64, err error) {
    src, err := os.Open(srcName)
    if err != nil {
        return  //没有Close
    }
 
    dst, err := os.Create(dstName)
    if err != nil {
        return //没有Close
    }
 
    written, err = io.Copy(dst, src)
    dst.Close()
    src.Close()
    return
}
Go用Defer确保打开的文件能被关闭：

 
func CopyFile(dstName, srcName string) (written int64, err error) {
    src, err := os.Open(srcName)
    if err != nil {
        return
    }
    defer src.Close()
 
    dst, err := os.Create(dstName)
    if err != nil {
        return
    }
    defer dst.Close()
 
    return io.Copy(dst, src)
}
defer语句预设一个延期调用的函数

 
for i := 0; i < 5; i++ {
    defer fmt.Printf("%d ", i)
}
```
被延期的函数通过后进先出（LIFO）的顺行执行，因此在返回时将打印4 3 2 1 0
```
### Panic/Recover
```
var user = os.Getenv("USER")

func init() {
    if user == ""{
        panic("no value for $USER")//panic接受一个任意类型（通常是字符串）作为程序死亡时要打印的东西
    }
}
```
对于不可恢复的错误，panic函数将立即停止当前函数的执行并开始逐级解开函数堆栈，同时运行所有被defer的函数。

如果这种解开达到堆栈的顶端，程序就死亡了。但是，可以使用recover函数来继续程序的执行。

recover会返回传递给panic的值。recover仅在被延期的defer函数内部才是有用的。

recover通常用来捕捉Painc，防止程序一下子挂掉。
```
 
func g(i int) {
    if i>1 {
        fmt.Println("Panic!")
        panic(fmt.Sprintf("%v", i)) //接收了一个数字
    }
 
}
 
func f() {
    defer func() {
        if r := recover(); r != nil {  //会接收到panic所接收到的值
            fmt.Println("Recovered in f", r)
        }
    }()
 
    for i := 0; i < 4; i++ {
        fmt.Println("Calling g with ", i)
        g(i)
        fmt.Println("Returned normally from g.")
    }
}
 
func main() {
    f()
    fmt.Println("Returned normally from f.")
}
//输出，Painc后的for循环没有继续执行了，但是main程序还在继续
Calling g with  0
Returned normally from g.
Calling g with  1
Returned normally from g.
Calling g with  2
Panic!
Recovered in f 2
Returned normally from f.
```
## 参考
https://coolshell.cn/articles/8460.html